ependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
  - OpenZeppelin/openzeppelin-contracts@3.4.0
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0'
dotenv: .env
networks:
  default: ropsten-fork-dev
  ropsten:
    verify: False
    capture_the_ether: '0x71c46Ed333C35e4E6c62D32dc7C8F00D125b4fee'
    deploy: '0x94D3232B38aEe06a2Fc0088C2B6b21041F73dc9e'
    call_me: '0x7690EEF3A8cE429f3DbEb34709fcF9698dEF6C00'
    nickname: '0x159ADB0dB8e63C866D9139318B60a175A2D6cFbE'
    guess_the_number: '0x49425c2D8bbbbc77e88057440E5D049c78646f4E'
    guess_the_random_number: '0x3738184D2B623238B7d5eead5C6FEA020531FA4e'
  ropsten-fork-dev:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}